import { Meeting } from '../types/meeting.js';

export const exportService = {
  /**
   * Formats meeting minutes into clean, professional Markdown.
   */
  toMarkdown(meeting: Meeting): string {
    const summary = meeting.summary;
    let md = `# ${meeting.title}\n\n`;
    md += `**Date:** ${summary?.date || new Date(meeting.createdAt).toLocaleDateString()} | **Duration:** ${meeting.duration} | **Generated by:** Minomeet AI (${summary?.modelUsed || 'Local'})\n\n`;

    if (summary?.attendees && summary.attendees.length > 0) {
      md += `### Attendees\n${summary.attendees.map(a => `- ${a}`).join('\n')}\n\n`;
    }

    if (summary?.summary) {
      md += `### Executive Summary\n${summary.summary}\n\n`;
    }

    if (summary?.keyDecisions && summary.keyDecisions.length > 0) {
      md += `### Key Decisions\n${summary.keyDecisions.map(d => `- ${d}`).join('\n')}\n\n`;
    }

    if (summary?.actionItems && summary.actionItems.length > 0) {
      md += `### Action Items\n| Owner | Task | Due Date | Notes | Status |\n|---|---|---|---|---|\n`;
      for (const act of summary.actionItems) {
        const status = act.completed ? '✅ Done' : '⏳ Pending';
        md += `| ${act.owner} | ${act.task} | ${act.due} | ${act.notes} | ${status} |\n`;
      }
      md += '\n';
    }

    if (summary?.discussionHighlights && summary.discussionHighlights.length > 0) {
      md += `### Discussion Highlights\n${summary.discussionHighlights.map(h => `- ${h}`).join('\n')}\n\n`;
    }

    if (meeting.transcript && meeting.transcript.length > 0) {
      md += `### Full Transcript\n`;
      for (const t of meeting.transcript) {
        md += `[${t.time}] ${t.speaker ? `**${t.speaker}:** ` : ''}${t.text}\n\n`;
      }
    }

    return md;
  },

  /**
   * Downloads content as a file.
   */
  downloadFile(content: string, filename: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  /**
   * Copies formatted text to clipboard.
   */
  async copyToClipboard(text: string): Promise<boolean> {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (e) {
      console.warn('Clipboard write failed, fallback to execCommand:', e);
      const textArea = document.createElement('textarea');
      textArea.value = text;
      document.body.appendChild(textArea);
      textArea.select();
      const success = document.execCommand('copy');
      document.body.removeChild(textArea);
      return success;
    }
  },

  /**
   * Opens clean printable page for browser print / Save as PDF.
   */
  printMeeting(meeting: Meeting) {
    const summary = meeting.summary;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${meeting.title} — Minomeet MOM</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #111827; line-height: 1.6; }
          h1 { font-size: 24px; margin-bottom: 4px; color: #1e3a8a; }
          .meta { font-size: 13px; color: #6b7280; margin-bottom: 24px; border-bottom: 1px solid #e5e7eb; padding-bottom: 12px; }
          h2 { font-size: 16px; margin: 20px 0 8px; color: #111827; border-bottom: 1px solid #f3f4f6; padding-bottom: 4px; }
          p { font-size: 14px; margin: 6px 0; }
          ul { margin: 6px 0; padding-left: 20px; font-size: 14px; }
          li { margin-bottom: 4px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
          th, td { border: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; }
          th { background: #f8fafc; font-weight: 600; }
          .footer { margin-top: 40px; font-size: 11px; color: #9aa2af; text-align: center; }
        </style>
      </head>
      <body>
        <h1>${meeting.title}</h1>
        <div class="meta">
          <span><b>Date:</b> ${summary?.date || new Date(meeting.createdAt).toLocaleDateString()}</span> &bull;
          <span><b>Duration:</b> ${meeting.duration}</span> &bull;
          <span><b>Model:</b> ${summary?.modelUsed || 'Minomeet On-Device AI'}</span>
        </div>

        ${summary?.summary ? `<h2>Executive Summary</h2><p>${summary.summary}</p>` : ''}

        ${summary?.keyDecisions && summary.keyDecisions.length > 0 ? `
          <h2>Key Decisions</h2>
          <ul>${summary.keyDecisions.map(d => `<li>${d}</li>`).join('')}</ul>
        ` : ''}

        ${summary?.actionItems && summary.actionItems.length > 0 ? `
          <h2>Action Items</h2>
          <table>
            <thead><tr><th>Owner</th><th>Task</th><th>Due Date</th><th>Notes</th></tr></thead>
            <tbody>
              ${summary.actionItems.map(a => `<tr><td>${a.owner}</td><td>${a.task}</td><td>${a.due}</td><td>${a.notes}</td></tr>`).join('')}
            </tbody>
          </table>
        ` : ''}

        ${summary?.discussionHighlights && summary.discussionHighlights.length > 0 ? `
          <h2>Discussion Highlights</h2>
          <ul>${summary.discussionHighlights.map(h => `<li>${h}</li>`).join('')}</ul>
        ` : ''}

        <div class="footer">Generated with Minomeet AI — Privacy-First Meeting Intelligence</div>
      </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
};

